FROM golang:1.26-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /build/unobot ./cmd/bot

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata && \
    addgroup -S unobot && adduser -S unobot -G unobot

USER unobot:unobot

WORKDIR /app
COPY --from=builder /build/unobot /app/unobot

ENTRYPOINT ["/app/unobot"]
