FROM --platform=$BUILDPLATFORM golang:1.26.3-bookworm AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -trimpath -ldflags="-w -s" -o /build/unobot ./cmd/bot

FROM gcr.io/distroless/static-debian12:nonroot
EXPOSE 8080

COPY --from=builder /build/unobot /unobot

ENTRYPOINT ["/unobot"]
