import { build } from 'vite'
import { mkdir, writeFile } from 'node:fs/promises'
try { await build() } finally {
 await mkdir(new URL('../dist/', import.meta.url), { recursive: true })
 await writeFile(new URL('../dist/.keep', import.meta.url), 'Frontend assets are generated by npm run build. This placeholder is not an application.\n')
}
